spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: '{cipher}211d0dd6b2c9f45d16de828ffbc48c046042694ccc94a0410ef875c5a41d9809'
    password: '{cipher}9295a9d85a456c1fb177e491018364a7e8220e3b448cab804067368205d2765e'
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    driver-class-name: com.mysql.jdbc.Driver